# SITE SETTINGS
title: BIG_PICTURE
author: BIG_PICTURE project partners

# SOCIAL PROFILES

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.1
repository: camera-traps/wildlifecamera.eu
posts_on_home: false
github_edit: true
colors:
  links: "#BF9260"
  banner: "#8A8764"
  footer: "#8A8764"
logo: /assets/logos/big_picture.png
font_serif: true

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
